----------------------------------------------------------------------------------------------------
-- This script inserts relational data into relational tables from nyc_bsm_staging table (which has nested JSON data).
-- Two temporary tables are deleted at the end of the script.
-- Relational tables 
--   nyc_bsm_core
--   nyc_bsm_partii
--   nyc_bsm_partii_crumbdata
----------------------------------------------------------------------------------------------------

--------------------------------------------------
-- create tables
--------------------------------------------------
CREATE TABLE IF NOT EXISTS nyc_bsm_core(
    bsmid string,
    VEHICLEROLE string,
    EVENTID string,
    EVENTTYPE string,
    EVENTMSGSEQNUM int,
    BSMRECORDMSGHEADERMYRFLEVEL int,
    BSMRECORDMSGHEADERAUTHENTICATED boolean,
    BSMRECORDBSMMSGCOREDATAMSGCNT int,
    BSMRECORDBSMMSGCOREDATAID string,
    BSMRECORDBSMMSGCOREDATAACCURACYSEMIMAJOR int,
    BSMRECORDBSMMSGCOREDATAACCURACYSEMIMINOR int,
    BSMRECORDBSMMSGCOREDATAACCURACYORIENTATION int,
    BSMRECORDBSMMSGCOREDATATRANSMISSION string,
    BSMRECORDBSMMSGCOREDATAANGLE int,
    BSMRECORDBSMMSGCOREDATAACCELSETLONG_MPSS double,
    BSMRECORDBSMMSGCOREDATAACCELSETLAT_MPSS double,
    BSMRECORDBSMMSGCOREDATAACCELSETVERT_MPSS double,
    BSMRECORDBSMMSGCOREDATAACCELSETYAW_DPS double,
    BSMRECORDBSMMSGCOREDATABRAKESWHEELBRAKES string,
    BSMRECORDBSMMSGCOREDATABRAKESTRACTION string,
    BSMRECORDBSMMSGCOREDATABRAKESABS string,
    BSMRECORDBSMMSGCOREDATABRAKESSCS string,
    BSMRECORDBSMMSGCOREDATABRAKESBRAKEBOOST string,
    BSMRECORDBSMMSGCOREDATABRAKESAUXBRAKES string,
    BSMRECORDBSMMSGCOREDATASIZEWIDTH string,
    BSMRECORDBSMMSGCOREDATASIZELENGTH string,
    BSMRECORDBSMMSGCOREDATAX_M double,
    BSMRECORDBSMMSGCOREDATAY_M double,
    BSMRECORDBSMMSGCOREDATAZ_M double,
    BSMRECORDBSMMSGCOREDATAT_S double,
    BSMRECORDBSMMSGCOREDATASPEED_MPS double,
    BSMRECORDBSMMSGCOREDATAHEADING_DEG double
);
    
CREATE TABLE IF NOT EXISTS nyc_bsm_partii(
    partiiid string,
    bsmid string,
    ID int,
    PATHPREDICTIONRADIUSOFCURVE bigint,
    PATHPREDICTIONCONFIDENCE int,
    CLASSIFICATION int,
    VEHICLEDATAHEIGHT int,
    VEHICLEDATAMASS int
);

CREATE TABLE IF NOT EXISTS nyc_bsm_partii_crumbdata(
    partiiid string,
    bsmid string,
    XOFFSET_M double,
    YOFFSET_M double,
    ZOFFSET_M double,
    TOFFSET_S double
);

--------------------------------------------------
-- drop the _tmp tables
--------------------------------------------------
DROP TABLE IF EXISTS nyc_bsm_tmp;
DROP TABLE IF EXISTS nyc_bsm_partii_tmp;

CREATE TABLE nyc_bsm_tmp 
STORED AS ORC tblproperties("orc.compress"="Zlib") 
AS SELECT 
    reflect("java.util.UUID", "randomUUID") bsmid, 
    * 
FROM nyc_bsm_staging;

INSERT INTO TABLE nyc_bsm_core
SELECT
    bsmid,
    VEHICLEROLE AS VEHICLEROLE,
    EVENTID AS EVENTID,
    EVENTTYPE AS EVENTTYPE,
    EVENTMSGSEQNUM AS EVENTMSGSEQNUM,
    BSMRECORD.MSGHEADER.MYRFLEVEL AS BSMRECORDMSGHEADERMYRFLEVEL,
    BSMRECORD.MSGHEADER.AUTHENTICATED AS BSMRECORDMSGHEADERAUTHENTICATED,
    BSMRECORD.BSMMSG.COREDATA.MSGCNT AS BSMRECORDBSMMSGCOREDATAMSGCNT,
    BSMRECORD.BSMMSG.COREDATA.ID AS BSMRECORDBSMMSGCOREDATAID,
    BSMRECORD.BSMMSG.COREDATA.ACCURACY.SEMIMAJOR AS BSMRECORDBSMMSGCOREDATAACCURACYSEMIMAJOR,
    BSMRECORD.BSMMSG.COREDATA.ACCURACY.SEMIMINOR AS BSMRECORDBSMMSGCOREDATAACCURACYSEMIMINOR,
    BSMRECORD.BSMMSG.COREDATA.ACCURACY.ORIENTATION AS BSMRECORDBSMMSGCOREDATAACCURACYORIENTATION,
    BSMRECORD.BSMMSG.COREDATA.TRANSMISSION AS BSMRECORDBSMMSGCOREDATATRANSMISSION,
    BSMRECORD.BSMMSG.COREDATA.ANGLE AS BSMRECORDBSMMSGCOREDATAANGLE,
    BSMRECORD.BSMMSG.COREDATA.ACCELSET.LONG_MPSS AS BSMRECORDBSMMSGCOREDATAACCELSETLONG_MPSS,
    BSMRECORD.BSMMSG.COREDATA.ACCELSET.LAT_MPSS AS BSMRECORDBSMMSGCOREDATAACCELSETLAT_MPSS,
    BSMRECORD.BSMMSG.COREDATA.ACCELSET.VERT_MPSS AS BSMRECORDBSMMSGCOREDATAACCELSETVERT_MPSS,
    BSMRECORD.BSMMSG.COREDATA.ACCELSET.YAW_DPS AS BSMRECORDBSMMSGCOREDATAACCELSETYAW_DPS,
    BSMRECORD.BSMMSG.COREDATA.BRAKES.WHEELBRAKES AS BSMRECORDBSMMSGCOREDATABRAKESWHEELBRAKES,
    BSMRECORD.BSMMSG.COREDATA.BRAKES.TRACTION AS BSMRECORDBSMMSGCOREDATABRAKESTRACTION,
    BSMRECORD.BSMMSG.COREDATA.BRAKES.ABS AS BSMRECORDBSMMSGCOREDATABRAKESABS,
    BSMRECORD.BSMMSG.COREDATA.BRAKES.SCS AS BSMRECORDBSMMSGCOREDATABRAKESSCS,
    BSMRECORD.BSMMSG.COREDATA.BRAKES.BRAKEBOOST AS BSMRECORDBSMMSGCOREDATABRAKESBRAKEBOOST,
    BSMRECORD.BSMMSG.COREDATA.BRAKES.AUXBRAKES AS BSMRECORDBSMMSGCOREDATABRAKESAUXBRAKES,
    BSMRECORD.BSMMSG.COREDATA.SIZE.WIDTH AS BSMRECORDBSMMSGCOREDATASIZEWIDTH,
    BSMRECORD.BSMMSG.COREDATA.SIZE.LENGTH AS BSMRECORDBSMMSGCOREDATASIZELENGTH,
    BSMRECORD.BSMMSG.COREDATA.X_M AS BSMRECORDBSMMSGCOREDATAX_M,
    BSMRECORD.BSMMSG.COREDATA.Y_M AS BSMRECORDBSMMSGCOREDATAY_M,
    BSMRECORD.BSMMSG.COREDATA.Z_M AS BSMRECORDBSMMSGCOREDATAZ_M,
    BSMRECORD.BSMMSG.COREDATA.T_S AS BSMRECORDBSMMSGCOREDATAT_S,
    BSMRECORD.BSMMSG.COREDATA.SPEED_MPS AS BSMRECORDBSMMSGCOREDATASPEED_MPS,
    BSMRECORD.BSMMSG.COREDATA.HEADING_DEG AS BSMRECORDBSMMSGCOREDATAHEADING_DEG
FROM nyc_bsm_tmp;

-- CREATE nyc_bsm part ii tmp

CREATE TABLE nyc_bsm_partii_tmp 
STORED AS ORC tblproperties ("orc.compress" = "Zlib")
AS SELECT 
    reflect("java.util.UUID","randomUUID") partiiid,
    bsmid,
    partii
FROM nyc_bsm_tmp 
LATERAL VIEW explode(BSMRECORD.BSMMSG.PARTII) sequenceArray AS partii;

-- insert part ii data into nyc_bsm part ii table

INSERT INTO TABLE nyc_bsm_partii
SELECT 
    partiiid,
    bsmid,
    partii.PARTIIID AS ID,
    partii.PARTIIVALUE.PATHPREDICTION.RADIUSOFCURVE AS PATHPREDICTIONRADIUSOFCURVE,
    partii.PARTIIVALUE.PATHPREDICTION.CONFIDENCE AS PATHPREDICTIONCONFIDENCE,
    partii.PARTIIVALUE.CLASSIFICATION AS CLASSIFICATION,
    partii.PARTIIVALUE.VEHICLEDATA.HEIGHT AS VEHICLEDATAHEIGHT,
    partii.PARTIIVALUE.VEHICLEDATA.MASS AS VEHICLEDATAMASS
FROM nyc_bsm_partii_tmp;

-- Insert crumb data into nyc_bsm part ii crumb data

INSERT INTO TABLE nyc_bsm_partii_crumbdata
SELECT
    partiiid,
    bsmid,
    cd.XOFFSET_M AS XOFFSET_M,
    cd.YOFFSET_M AS YOFFSET_M,
    cd.ZOFFSET_M AS ZOFFSET_M,
    cd.TOFFSET_S AS TOFFSET_S
FROM nyc_bsm_partii_tmp
LATERAL VIEW explode (partii.PARTIIVALUE.PATHHISTORY.CRUMBDATA) cdArray AS cd;

--DROP temperary tables. 

DROP TABLE IF EXISTS nyc_bsm_tmp;
DROP TABLE IF EXISTS nyc_bsm_partii_tmp;