----------------------------------------------------------------------------------------------------
-- This script inserts relational data into relational tables from thea_sentsrm_staging table (which has nested JSON data).
-- Two temporary tables are deleted at the end of the script.
-- Relational tables 
--   thea_sentsrm_core
----------------------------------------------------------------------------------------------------

--------------------------------------------------
-- create tables
--------------------------------------------------
CREATE TABLE IF NOT EXISTS thea_sentsrm_core(
    srmid string,
    METADATALOGUPLOADEDAT timestamp,
    METADATAMSGCNT int,
    METADATABURSTCNT int,
    METADATABURSTID bigint,
    METADATAHOSTVEHICLEID string,
    METADATALOGPSID string,
    METADATARSULIST string,
    METADATARECEIVEDRSUTIMESTAMPS bigint,
    METADATADATALOGID string,
    METADATALOGGENERATEDAT timestamp,
    METADATAEVENTTYPE string,
    DOT3CHANNEL int,
    DOT3PSID string,
    DOT3SIGNALRXSTRENGTH int,
    DOT3DATARATE int,
    DOT3TIMESLOT int,
    MESSAGEFRAMEMESSAGEID int,
    DATATIMESTAMP int,
    DATASECOND int,
    DATASEQUENCENUMBER int,
    DATAREQUESTSREQUESTID int,
    DATAREQUESTREQUESTREQUESTID int,
    DATAREQUESTREQUESTREQUESTTYPE string,
    DATAREQUESTREQUESTINBOUNDLANE int,
    DATAREQUESTREQUESTOUTBOUNDLANE int,
    DATAREQUESTSMINUTE int,
    DATAREQUESTSSECOND int,
    DATAREQUESTSDURATION int,
    DATAREQUESTORENTITYID int,
    DATAREQUESTORTYPEROLE string,
    DATAREQUESTORTYPEREQUEST string,
    DATAREQUESTORPOSITIONLAT bigint,
    DATAREQUESTORPOSITIONLONG bigint,
    DATAREQUESTORPOSITIONELEVATION int,
    DATAREQUESTORPOSITIONHEADING int,
    DATAREQUESTORNAME string
);

--------------------------------------------------
-- drop the _tmp tables
--------------------------------------------------
DROP TABLE IF EXISTS thea_sentsrm_tmp;

CREATE TABLE thea_sentsrm_tmp 
STORED AS ORC tblproperties("orc.compress"="Zlib") 
AS SELECT 
    reflect("java.util.UUID", "randomUUID") srmid, 
    * 
FROM thea_sentsrm_staging;

INSERT INTO TABLE thea_sentsrm_core
SELECT
    srmid,
    cast(replace(replace(METADATA.LOGUPLOADEDAT, 'T', ' '), 'Z', '') as timestamp) AS METADATALOGUPLOADEDAT,
    METADATA.MSGCNT AS METADATAMSGCNT,
    METADATA.BURSTCNT AS METADATABURSTCNT,
    METADATA.BURSTID AS METADATABURSTID,
    METADATA.HOSTVEHICLEID AS METADATAHOSTVEHICLEID,
    METADATA.LOGPSID AS METADATALOGPSID,
    METADATA.RSULIST AS METADATARSULIST,
    METADATA.RECEIVEDRSUTIMESTAMPS AS METADATARECEIVEDRSUTIMESTAMPS,
    METADATA.DATALOGID AS METADATADATALOGID,
    cast(replace(replace(METADATA.LOGGENERATEDAT, 'T', ' '), 'Z', '') as timestamp) AS METADATALOGGENERATEDAT,
    METADATA.EVENTTYPE AS METADATAEVENTTYPE,
    METADATA.DOT3.CHANNEL AS DOT3CHANNEL,
    METADATA.DOT3.PSID AS DOT3PSID,
    METADATA.DOT3.SIGNAL.RXSTRENGTH AS DOT3SIGNALRXSTRENGTH,
    METADATA.DOT3.DATARATE AS DOT3DATARATE,
    METADATA.DOT3.TIMESLOT AS DOT3TIMESLOT,
    PAYLOAD.MESSAGEFRAME.MESSAGEID AS MESSAGEFRAMEMESSAGEID,
    PAYLOAD.MESSAGEFRAME.VALUE.SIGNALREQUESTMESSAGE.TIMESTAMPP AS DATATIMESTAMP,
    PAYLOAD.MESSAGEFRAME.VALUE.SIGNALREQUESTMESSAGE.SECOND AS DATASECOND,
    PAYLOAD.MESSAGEFRAME.VALUE.SIGNALREQUESTMESSAGE.SEQUENCENUMBER AS DATASEQUENCENUMBER,
    PAYLOAD.MESSAGEFRAME.VALUE.SIGNALREQUESTMESSAGE.REQUESTS.SIGNALREQUESTPACKAGE.REQUEST.ID.ID AS DATAREQUESTSREQUESTID,
    PAYLOAD.MESSAGEFRAME.VALUE.SIGNALREQUESTMESSAGE.REQUESTS.SIGNALREQUESTPACKAGE.REQUEST.REQUESTID AS DATAREQUESTREQUESTREQUESTID,
    PAYLOAD.MESSAGEFRAME.VALUE.SIGNALREQUESTMESSAGE.REQUESTS.SIGNALREQUESTPACKAGE.REQUEST.REQUESTTYPE AS DATAREQUESTREQUESTREQUESTTYPE,
    PAYLOAD.MESSAGEFRAME.VALUE.SIGNALREQUESTMESSAGE.REQUESTS.SIGNALREQUESTPACKAGE.REQUEST.INBOUNDLANE.LANE AS DATAREQUESTREQUESTINBOUNDLANE,
    PAYLOAD.MESSAGEFRAME.VALUE.SIGNALREQUESTMESSAGE.REQUESTS.SIGNALREQUESTPACKAGE.REQUEST.OUTBOUNDLANE.LANE AS DATAREQUESTREQUESTOUTBOUNDLANE,
    PAYLOAD.MESSAGEFRAME.VALUE.SIGNALREQUESTMESSAGE.REQUESTS.SIGNALREQUESTPACKAGE.MINUTE AS DATAREQUESTSMINUTE,
    PAYLOAD.MESSAGEFRAME.VALUE.SIGNALREQUESTMESSAGE.REQUESTS.SIGNALREQUESTPACKAGE.SECOND AS DATAREQUESTSSECOND,
    PAYLOAD.MESSAGEFRAME.VALUE.SIGNALREQUESTMESSAGE.REQUESTS.SIGNALREQUESTPACKAGE.DURATION AS DATAREQUESTSDURATION,
    PAYLOAD.MESSAGEFRAME.VALUE.SIGNALREQUESTMESSAGE.REQUESTOR.ID.ENTITYID AS DATAREQUESTORENTITYID,
    PAYLOAD.MESSAGEFRAME.VALUE.SIGNALREQUESTMESSAGE.REQUESTOR.TYPE.ROLE AS DATAREQUESTORTYPEROLE,
    PAYLOAD.MESSAGEFRAME.VALUE.SIGNALREQUESTMESSAGE.REQUESTOR.TYPE.REQUEST AS ATAREQUESTORTYPEREQUEST,
    PAYLOAD.MESSAGEFRAME.VALUE.SIGNALREQUESTMESSAGE.REQUESTOR.POSITION.POSITION.LAT AS DATAREQUESTORPOSITIONLAT,
    PAYLOAD.MESSAGEFRAME.VALUE.SIGNALREQUESTMESSAGE.REQUESTOR.POSITION.POSITION.LONG AS DATAREQUESTORPOSITIONLONG,
    PAYLOAD.MESSAGEFRAME.VALUE.SIGNALREQUESTMESSAGE.REQUESTOR.POSITION.POSITION.ELEVATION AS DATAREQUESTORPOSITIONELEVATION,
    PAYLOAD.MESSAGEFRAME.VALUE.SIGNALREQUESTMESSAGE.REQUESTOR.POSITION.HEADING AS DATAREQUESTORPOSITIONHEADING,
    PAYLOAD.MESSAGEFRAME.VALUE.SIGNALREQUESTMESSAGE.REQUESTOR.NAME AS DATAREQUESTORNAME
FROM thea_sentsrm_tmp;

--DROP temperary tables. 

DROP TABLE IF EXISTS thea_sentsrm_tmp;