----------------------------------------------------------------------------------------------------
-- This script creates the relation tables if they do not exist
-- This script inserts relational data into relational tables from thea_warningeebl_staging table (which has nested JSON data).
-- One temporary tables are deleted at the end of the script.
-- Relational tables 
--   nyc_eventfcw_core
----------------------------------------------------------------------------------------------------

--------------------------------------------------
-- nyc_eventfcw_core
--------------------------------------------------
CREATE TABLE IF NOT EXISTS nyc_eventfcw_core(
    EVENTID string,
    EVENTHEADERLOCATIONSOURCE string,
    EVENTHEADERASDFIRMWAREVERSION string,
    EVENTHEADEREVENTALERTACTIVE boolean,
    EVENTHEADEREVENTALERTSENT boolean,
    EVENTHEADEREVENTALERTHEARD boolean,
    EVENTHEADERHOSTVEHID string,
    EVENTHEADERTARGETVEHID string,
    EVENTHEADERTRIGGERHVSEQNUM int,
    EVENTHEADERTRIGGERTVSEQNUM int,
    EVENTHEADEREVENTTYPE string,
    EVENTHEADERPARAMETERSRECORDINGROI string,
    EVENTHEADERPARAMETERSTIMERECORDBEFORE string,
    EVENTHEADERPARAMETERSTIMERECORDFOLLOW string,
    EVENTHEADERPARAMETERSTIMERECORDRESOLUTION string,
    EVENTHEADERPARAMETERSMINSPDTHRESHOLD string,
    EVENTHEADERPARAMETERSTIMETOCRASH string,
    EVENTHEADERGRPID int,
    EVENTHEADEREVENTSTATUS string,
    EVENTHEADEREVENTTIMEBIN string,
    EVENTHEADEREVENTLOCATIONBIN string,
    EVENTHEADERWEATHERCONDITION string,
    EVENTHEADERAIRTEMPURATURE int,
    EVENTHEADERPRECIPITATION1HR string,
    EVENTHEADERWINDSPEED string
);

--------------------------------------------------
-- INSERT INTO RELATIONAL TABLE
--------------------------------------------------

DROP TABLE IF EXISTS nyc_eventfcw_tmp;

CREATE TABLE nyc_eventfcw_tmp 
STORED AS ORC tblproperties("orc.compress"="Zlib") 
AS SELECT 
    * 
FROM nyc_eventfcw_staging;

INSERT INTO TABLE nyc_eventfcw_core
SELECT
    EVENTID AS EVENTID,
    EVENTHEADER.LOCATIONSOURCE AS EVENTHEADERLOCATIONSOURCE,
    EVENTHEADER.ASDFIRMWAREVERSION AS EVENTHEADERASDFIRMWAREVERSION,
    EVENTHEADER.EVENTALERTACTIVE AS EVENTHEADEREVENTALERTACTIVE,
    EVENTHEADER.EVENTALERTSENT AS EVENTHEADEREVENTALERTSENT,
    EVENTHEADER.EVENTALERTHEARD AS EVENTHEADEREVENTALERTHEARD,
    EVENTHEADER.HOSTVEHID AS EVENTHEADERHOSTVEHID,
    EVENTHEADER.TARGETVEHID AS EVENTHEADERTARGETVEHID,
    EVENTHEADER.TRIGGERHVSEQNUM AS EVENTHEADERTRIGGERHVSEQNUM,
    EVENTHEADER.TRIGGERTVSEQNUM AS EVENTHEADERTRIGGERTVSEQNUM,
    EVENTHEADER.EVENTTYPE AS EVENTHEADEREVENTTYPE,
    EVENTHEADER.PARAMETERS.RECORDINGROI AS EVENTHEADERPARAMETERSRECORDINGROI,
    EVENTHEADER.PARAMETERS.TIMERECORDBEFORE AS EVENTHEADERPARAMETERSTIMERECORDBEFORE,
    EVENTHEADER.PARAMETERS.TIMERECORDFOLLOW AS EVENTHEADERPARAMETERSTIMERECORDFOLLOW,
    EVENTHEADER.PARAMETERS.TIMERECORDRESOLUTION AS EVENTHEADERPARAMETERSTIMERECORDRESOLUTION,
    EVENTHEADER.PARAMETERS.MINSPDTHRESHOLD AS EVENTHEADERPARAMETERSMINSPDTHRESHOLD,
    EVENTHEADER.PARAMETERS.TIMETOCRASH AS EVENTHEADERPARAMETERSTIMETOCRASH,
    EVENTHEADER.GRPID AS EVENTHEADERGRPID,
    EVENTHEADER.EVENTSTATUS AS EVENTHEADEREVENTSTATUS,
    EVENTHEADER.EVENTTIMEBIN AS EVENTHEADEREVENTTIMEBIN,
    EVENTHEADER.EVENTLOCATIONBIN AS EVENTHEADEREVENTLOCATIONBIN,
    EVENTHEADER.WEATHERCONDITION AS EVENTHEADERWEATHERCONDITION,
    EVENTHEADER.AIRTEMPURATURE AS EVENTHEADERAIRTEMPURATURE,
    EVENTHEADER.PRECIPITATION1HR AS EVENTHEADERPRECIPITATION1HR,
    EVENTHEADER.WINDSPEED AS EVENTHEADERWINDSPEED
FROM nyc_eventfcw_tmp;

--DROP temperary tables. 

DROP TABLE IF EXISTS nyc_eventfcw_tmp;
